#!/bin/bash

#sudo pip install pelican
#sudo pip install ghp-import
#sudo pip install markdown
if [[ $1 != 'my' ]];then
pelican content
fi
ghp-import output
git push -f git@github.com:xyw1/xyw1.github.io.git  gh-pages:master 
